import type { CountryCode } from './mortgage';

export type AppLocale = 'en-US' | 'en-GB' | 'en-CA' | 'fr-CA' | 'de-DE' | 'fr-FR' | 'es-ES';
type Copy = Record<'calculator' | 'methodology' | 'localRules' | 'estimate' | 'monthlyPayment' | 'principalInterest' | 'totalInterest' | 'totalPaid' | 'payoffTime' | 'downloadCsv' | 'downloadPdf' | 'share' | 'comparePlans' | 'amortization' | 'sources' | 'privacy' | 'legal' | 'estimateOnly', string> & Partial<Record<'loanAmount' | 'interestRate' | 'term' | 'extraPayment' | 'repaymentType', string>>;

export const localeCopy: Record<AppLocale, Copy> = {
  'en-US': { calculator: 'Calculator', methodology: 'Methodology', localRules: 'Local rules', estimate: 'Live estimate', monthlyPayment: 'Estimated monthly payment', principalInterest: 'Principal and interest, before recurring property costs', totalInterest: 'Total interest', totalPaid: 'Total paid', payoffTime: 'Payoff time', downloadCsv: 'Download amortization CSV', downloadPdf: 'Download PDF estimate', share: 'Copy share link', comparePlans: 'Compare plans', amortization: 'Amortization preview', sources: 'Sources and assumptions', privacy: 'Privacy', legal: 'Legal notice', estimateOnly: 'Estimate only. Not a loan offer, tax opinion, or financial advice.', loanAmount: 'Loan amount', interestRate: 'Interest rate', term: 'Amortization term', extraPayment: 'Extra payment each month', repaymentType: 'Repayment type' },
  'en-GB': { calculator: 'Calculator', methodology: 'Methodology', localRules: 'Local rules', estimate: 'Live estimate', monthlyPayment: 'Estimated monthly payment', principalInterest: 'Principal and interest, before recurring property costs', totalInterest: 'Total interest', totalPaid: 'Total paid', payoffTime: 'Payoff time', downloadCsv: 'Download amortization CSV', downloadPdf: 'Download PDF estimate', share: 'Copy share link', comparePlans: 'Compare plans', amortization: 'Amortization preview', sources: 'Sources and assumptions', privacy: 'Privacy', legal: 'Legal notice', estimateOnly: 'Estimate only. Not a loan offer, tax opinion, or financial advice.' },
  'en-CA': { calculator: 'Calculator', methodology: 'Methodology', localRules: 'Local rules', estimate: 'Live estimate', monthlyPayment: 'Estimated monthly payment', principalInterest: 'Principal and interest, before recurring property costs', totalInterest: 'Total interest', totalPaid: 'Total paid', payoffTime: 'Payoff time', downloadCsv: 'Download amortization CSV', downloadPdf: 'Download PDF estimate', share: 'Copy share link', comparePlans: 'Compare plans', amortization: 'Amortization preview', sources: 'Sources and assumptions', privacy: 'Privacy', legal: 'Legal notice', estimateOnly: 'Estimate only. Not a loan offer, tax opinion, or financial advice.' },
  'fr-CA': { calculator: 'Calculatrice', methodology: 'Méthodologie', localRules: 'Règles locales', estimate: 'Estimation en direct', monthlyPayment: 'Paiement mensuel estimé', principalInterest: 'Capital et intérêts, avant les frais récurrents', totalInterest: 'Intérêts totaux', totalPaid: 'Total payé', payoffTime: 'Durée de remboursement', downloadCsv: 'Télécharger le CSV du tableau', downloadPdf: 'Télécharger l’estimation PDF', share: 'Copier le lien de partage', comparePlans: 'Comparer les scénarios', amortization: 'Aperçu de l’amortissement', sources: 'Sources et hypothèses', privacy: 'Confidentialité', legal: 'Mentions légales', estimateOnly: 'Estimation seulement. Ce n’est pas une offre de prêt, un avis fiscal ou un conseil financier.', loanAmount: 'Montant du prêt', interestRate: 'Taux d’intérêt', term: 'Période d’amortissement', extraPayment: 'Versement supplémentaire mensuel', repaymentType: 'Type de remboursement' },
  'de-DE': { calculator: 'Rechner', methodology: 'Methodik', localRules: 'Lokale Regeln', estimate: 'Live-Schätzung', monthlyPayment: 'Geschätzte Monatsrate', principalInterest: 'Tilgung und Zinsen, vor laufenden Nebenkosten', totalInterest: 'Zinsen gesamt', totalPaid: 'Gesamtbetrag', payoffTime: 'Laufzeit bis Rückzahlung', downloadCsv: 'Tilgungsplan als CSV laden', downloadPdf: 'PDF-Schätzung herunterladen', share: 'Freigabelink kopieren', comparePlans: 'Szenarien vergleichen', amortization: 'Tilgungsplan-Vorschau', sources: 'Quellen und Annahmen', privacy: 'Datenschutz', legal: 'Impressum', estimateOnly: 'Nur eine Schätzung. Kein Kreditangebot, Steuerurteil oder Finanzberatung.', loanAmount: 'Darlehensbetrag', interestRate: 'Zinssatz', term: 'Tilgungsdauer', extraPayment: 'Zusätzliche Monatszahlung', repaymentType: 'Rückzahlungsart' },
  'fr-FR': { calculator: 'Calculatrice', methodology: 'Méthodologie', localRules: 'Règles locales', estimate: 'Estimation en direct', monthlyPayment: 'Mensualité estimée', principalInterest: 'Capital et intérêts, hors coûts récurrents', totalInterest: 'Intérêts totaux', totalPaid: 'Total payé', payoffTime: 'Durée de remboursement', downloadCsv: 'Télécharger le tableau CSV', downloadPdf: 'Télécharger l’estimation PDF', share: 'Copier le lien de partage', comparePlans: 'Comparer les scénarios', amortization: 'Aperçu de l’amortissement', sources: 'Sources et hypothèses', privacy: 'Confidentialité', legal: 'Mentions légales', estimateOnly: 'Estimation uniquement. Ce n’est pas une offre de prêt, un avis fiscal ou un conseil financier.', loanAmount: 'Montant du prêt', interestRate: 'Taux d’intérêt', term: 'Durée d’amortissement', extraPayment: 'Versement supplémentaire mensuel', repaymentType: 'Type de remboursement' },
  'es-ES': { calculator: 'Calculadora', methodology: 'Metodología', localRules: 'Normas locales', estimate: 'Estimación en directo', monthlyPayment: 'Cuota mensual estimada', principalInterest: 'Capital e intereses, antes de costes periódicos', totalInterest: 'Intereses totales', totalPaid: 'Total pagado', payoffTime: 'Plazo de amortización', downloadCsv: 'Descargar cuadro CSV', downloadPdf: 'Descargar estimación en PDF', share: 'Copiar enlace para compartir', comparePlans: 'Comparar escenarios', amortization: 'Vista previa de amortización', sources: 'Fuentes y supuestos', privacy: 'Privacidad', legal: 'Aviso legal', estimateOnly: 'Solo una estimación. No es una oferta de préstamo, opinión fiscal ni asesoramiento financiero.', loanAmount: 'Importe del préstamo', interestRate: 'Tipo de interés', term: 'Plazo de amortización', extraPayment: 'Pago adicional mensual', repaymentType: 'Tipo de reembolso' },
};

export const localeCountry: Record<AppLocale, CountryCode> = { 'en-US': 'US', 'en-GB': 'GB', 'en-CA': 'CA', 'fr-CA': 'CA', 'de-DE': 'DE', 'fr-FR': 'FR', 'es-ES': 'ES' };
