import type { CountryCode } from './mortgage';

export type AppLocale = 'en-US' | 'en-GB' | 'en-CA' | 'fr-CA' | 'de-DE' | 'fr-FR' | 'es-ES';
type Copy = Record<'calculator' | 'methodology' | 'localRules' | 'estimate' | 'monthlyPayment' | 'principalInterest' | 'totalInterest' | 'totalPaid' | 'payoffTime' | 'downloadCsv' | 'downloadPdf' | 'share' | 'comparePlans' | 'amortization' | 'sources' | 'privacy' | 'legal' | 'estimateOnly' | 'loanAmount' | 'interestRate' | 'term' | 'extraPayment' | 'repaymentType', string>;

export type FaqItem = { question: string; answer: string };
export type SeoCopy = { title: string; description: string; heading: string; intro: string };

export const localeCopy: Record<AppLocale, Copy> = {
  'en-US': { calculator: 'Calculator', methodology: 'Methodology', localRules: 'Local rules', estimate: 'Live estimate', monthlyPayment: 'Estimated monthly payment', principalInterest: 'Principal and interest, before recurring property costs', totalInterest: 'Total interest', totalPaid: 'Total paid', payoffTime: 'Payoff time', downloadCsv: 'Download amortization CSV', downloadPdf: 'Download PDF estimate', share: 'Copy share link', comparePlans: 'Compare plans', amortization: 'Amortization preview', sources: 'Sources and assumptions', privacy: 'Privacy', legal: 'Legal notice', estimateOnly: 'Estimate only. Not a loan offer, tax opinion, or financial advice.', loanAmount: 'Loan amount', interestRate: 'Interest rate', term: 'Amortization term', extraPayment: 'Extra payment each month', repaymentType: 'Repayment type' },
  'en-GB': { calculator: 'Calculator', methodology: 'Methodology', localRules: 'Local rules', estimate: 'Live estimate', monthlyPayment: 'Estimated monthly payment', principalInterest: 'Principal and interest, before recurring property costs', totalInterest: 'Total interest', totalPaid: 'Total paid', payoffTime: 'Payoff time', downloadCsv: 'Download amortization CSV', downloadPdf: 'Download PDF estimate', share: 'Copy share link', comparePlans: 'Compare plans', amortization: 'Amortization preview', sources: 'Sources and assumptions', privacy: 'Privacy', legal: 'Legal notice', estimateOnly: 'Estimate only. Not a loan offer, tax opinion, or financial advice.', loanAmount: 'Loan amount', interestRate: 'Interest rate', term: 'Mortgage term', extraPayment: 'Extra payment each month', repaymentType: 'Repayment type' },
  'en-CA': { calculator: 'Calculator', methodology: 'Methodology', localRules: 'Local rules', estimate: 'Live estimate', monthlyPayment: 'Estimated monthly payment', principalInterest: 'Principal and interest, before recurring property costs', totalInterest: 'Total interest', totalPaid: 'Total paid', payoffTime: 'Payoff time', downloadCsv: 'Download amortization CSV', downloadPdf: 'Download PDF estimate', share: 'Copy share link', comparePlans: 'Compare plans', amortization: 'Amortization preview', sources: 'Sources and assumptions', privacy: 'Privacy', legal: 'Legal notice', estimateOnly: 'Estimate only. Not a loan offer, tax opinion, or financial advice.', loanAmount: 'Mortgage amount', interestRate: 'Interest rate', term: 'Amortization period', extraPayment: 'Extra payment each month', repaymentType: 'Payment type' },
  'fr-CA': { calculator: 'Calculatrice', methodology: 'Méthodologie', localRules: 'Règles locales', estimate: 'Estimation en direct', monthlyPayment: 'Paiement mensuel estimé', principalInterest: 'Capital et intérêts, avant les frais récurrents', totalInterest: 'Intérêts totaux', totalPaid: 'Total payé', payoffTime: 'Durée de remboursement', downloadCsv: 'Télécharger le CSV du tableau', downloadPdf: 'Télécharger l’estimation PDF', share: 'Copier le lien de partage', comparePlans: 'Comparer les scénarios', amortization: 'Aperçu de l’amortissement', sources: 'Sources et hypothèses', privacy: 'Confidentialité', legal: 'Mentions légales', estimateOnly: 'Estimation seulement. Ce n’est pas une offre de prêt, un avis fiscal ou un conseil financier.', loanAmount: 'Montant du prêt', interestRate: 'Taux d’intérêt', term: 'Période d’amortissement', extraPayment: 'Versement supplémentaire mensuel', repaymentType: 'Type de remboursement' },
  'de-DE': { calculator: 'Rechner', methodology: 'Methodik', localRules: 'Lokale Regeln', estimate: 'Live-Schätzung', monthlyPayment: 'Geschätzte Monatsrate', principalInterest: 'Tilgung und Zinsen, vor laufenden Nebenkosten', totalInterest: 'Zinsen gesamt', totalPaid: 'Gesamtbetrag', payoffTime: 'Laufzeit bis Rückzahlung', downloadCsv: 'Tilgungsplan als CSV laden', downloadPdf: 'PDF-Schätzung herunterladen', share: 'Freigabelink kopieren', comparePlans: 'Szenarien vergleichen', amortization: 'Tilgungsplan-Vorschau', sources: 'Quellen und Annahmen', privacy: 'Datenschutz', legal: 'Impressum', estimateOnly: 'Nur eine Schätzung. Kein Kreditangebot, Steuerurteil oder Finanzberatung.', loanAmount: 'Darlehensbetrag', interestRate: 'Zinssatz', term: 'Tilgungsdauer', extraPayment: 'Zusätzliche Monatszahlung', repaymentType: 'Rückzahlungsart' },
  'fr-FR': { calculator: 'Calculatrice', methodology: 'Méthodologie', localRules: 'Règles locales', estimate: 'Estimation en direct', monthlyPayment: 'Mensualité estimée', principalInterest: 'Capital et intérêts, hors coûts récurrents', totalInterest: 'Intérêts totaux', totalPaid: 'Total payé', payoffTime: 'Durée de remboursement', downloadCsv: 'Télécharger le tableau CSV', downloadPdf: 'Télécharger l’estimation PDF', share: 'Copier le lien de partage', comparePlans: 'Comparer les scénarios', amortization: 'Aperçu de l’amortissement', sources: 'Sources et hypothèses', privacy: 'Confidentialité', legal: 'Mentions légales', estimateOnly: 'Estimation uniquement. Ce n’est pas une offre de prêt, un avis fiscal ou un conseil financier.', loanAmount: 'Montant du prêt', interestRate: 'Taux d’intérêt', term: 'Durée d’amortissement', extraPayment: 'Versement supplémentaire mensuel', repaymentType: 'Type de remboursement' },
  'es-ES': { calculator: 'Calculadora', methodology: 'Metodología', localRules: 'Normas locales', estimate: 'Estimación en directo', monthlyPayment: 'Cuota mensual estimada', principalInterest: 'Capital e intereses, antes de costes periódicos', totalInterest: 'Intereses totales', totalPaid: 'Total pagado', payoffTime: 'Plazo de amortización', downloadCsv: 'Descargar cuadro CSV', downloadPdf: 'Descargar estimación en PDF', share: 'Copiar enlace para compartir', comparePlans: 'Comparar escenarios', amortization: 'Vista previa de amortización', sources: 'Fuentes y supuestos', privacy: 'Privacidad', legal: 'Aviso legal', estimateOnly: 'Solo una estimación. No es una oferta de préstamo, opinión fiscal ni asesoramiento financiero.', loanAmount: 'Importe del préstamo', interestRate: 'Tipo de interés', term: 'Plazo de amortización', extraPayment: 'Pago adicional mensual', repaymentType: 'Tipo de reembolso' },
};

export const localeCountry: Record<AppLocale, CountryCode> = { 'en-US': 'US', 'en-GB': 'GB', 'en-CA': 'CA', 'fr-CA': 'CA', 'de-DE': 'DE', 'fr-FR': 'FR', 'es-ES': 'ES' };

export const localeSeo: Record<AppLocale, SeoCopy> = {
  'en-US': { title: 'Mortgage calculator with extra payments and amortization', description: 'Calculate mortgage payments with extra principal, taxes, insurance, PMI and HOA costs. Compare payoff time and download a full amortization schedule.', heading: 'Mortgage calculator with extra payments', intro: 'See your monthly payment, full amortization schedule, and how extra principal can reduce interest and shorten your payoff time.' },
  'en-GB': { title: 'UK mortgage repayment calculator with SDLT estimate', description: 'Estimate UK mortgage repayments, total interest and overpayment savings, with SDLT, LBTT or LTT shown separately for your selected location.', heading: 'UK mortgage repayment calculator with overpayments', intro: 'Compare monthly repayments and overpayment savings, then estimate SDLT, Scottish LBTT or Welsh LTT separately from the mortgage.' },
  'en-CA': { title: 'Canadian mortgage calculator with extra payments', description: 'Calculate Canadian mortgage payments using semi-annual compounding. Compare monthly, biweekly and accelerated schedules with extra payments.', heading: 'Canadian mortgage calculator with extra payments', intro: 'Compare monthly, biweekly and accelerated payments using the Canadian semi-annual compounding convention, with a complete amortization schedule.' },
  'fr-CA': { title: 'Calculatrice hypothécaire Canada avec paiements accélérés', description: 'Calculez les paiements hypothécaires au Canada avec capitalisation semestrielle, versements supplémentaires et fréquences accélérées.', heading: 'Calculatrice hypothécaire canadienne avec versements supplémentaires', intro: 'Comparez les paiements mensuels, aux deux semaines et accélérés avec la capitalisation semestrielle canadienne et un tableau d’amortissement.' },
  'de-DE': { title: 'Baufinanzierungsrechner mit Sondertilgung und Nebenkosten', description: 'Monatsrate, Zinsen und Restschuld mit Sondertilgung berechnen. Grunderwerbsteuer nach Bundesland wird getrennt ausgewiesen.', heading: 'Baufinanzierungsrechner mit Sondertilgung', intro: 'Berechnen Sie Monatsrate, Zinskosten und Restschuld und vergleichen Sie, wie Sondertilgungen Laufzeit und Gesamtzinsen reduzieren.' },
  'fr-FR': { title: 'Calculatrice de prêt immobilier avec remboursement anticipé', description: 'Calculez les mensualités, le coût des intérêts et le gain des versements supplémentaires, avec estimation des droits de mutation.', heading: 'Calculatrice de prêt immobilier avec versements supplémentaires', intro: 'Comparez les mensualités, le coût total et la durée gagnée grâce aux remboursements supplémentaires.' },
  'es-ES': { title: 'Calculadora de hipoteca con amortización anticipada e ITP', description: 'Calcula la cuota, los intereses y el ahorro por pagos extra. Estima también ITP o AJD según la comunidad autónoma.', heading: 'Calculadora de hipoteca con amortización anticipada', intro: 'Compara cuotas, intereses y plazo con pagos adicionales y consulta por separado una estimación de ITP o AJD.' },
};

const englishFaq: FaqItem[] = [
  { question: 'Is this a mortgage offer?', answer: 'No. This is an illustrative estimate, not a loan offer, tax opinion, legal advice or financial advice.' },
  { question: 'What is included in the monthly payment?', answer: 'The main result includes principal and interest. US users may add property tax, home insurance, HOA fees and flood insurance. Transaction taxes and other closing costs are shown separately when supported.' },
  { question: 'Why can my lender quote be different?', answer: 'Lenders may use different compounding, payment dates, daily-interest rules, fees, insurance premiums, product rates and rounding. Use the estimate for comparison and confirm the final figures with your lender.' },
  { question: 'How do extra payments affect the mortgage?', answer: 'When your agreement allows extra principal payments, they can reduce the balance sooner, lower later interest and shorten the payoff period. Check for overpayment limits or early-repayment charges.' },
  { question: 'Do local taxes vary?', answer: 'Yes. Transfer taxes, property taxes, insurance and eligibility rules vary by country, state, province, municipality or autonomous community and may change after our review date.' },
  { question: 'Is my calculator data stored?', answer: 'Calculations run in your browser. A share link places the selected calculation inputs in the URL, so treat that URL as information you have chosen to share.' },
];

export const localeFaq: Record<AppLocale, FaqItem[]> = {
  'en-US': englishFaq,
  'en-GB': englishFaq,
  'en-CA': englishFaq,
  'fr-CA': [
    { question: 'S’agit-il d’une offre hypothécaire ?', answer: 'Non. Il s’agit d’une estimation illustrative, et non d’une offre de prêt ni d’un conseil fiscal, juridique ou financier.' },
    { question: 'Que comprend le paiement mensuel ?', answer: 'Le résultat principal comprend le capital et les intérêts. Les taxes de transfert et les autres frais de clôture sont affichés séparément lorsqu’ils sont pris en charge.' },
    { question: 'Pourquoi l’offre du prêteur peut-elle différer ?', answer: 'Les prêteurs peuvent appliquer d’autres dates de paiement, frais, primes, taux et règles d’arrondi. Confirmez toujours les chiffres définitifs avec votre prêteur.' },
    { question: 'Quel est l’effet des versements supplémentaires ?', answer: 'S’ils sont permis, ils peuvent réduire plus rapidement le capital, les intérêts futurs et la durée de remboursement. Vérifiez les limites et pénalités.' },
    { question: 'Les taxes locales varient-elles ?', answer: 'Oui. Les taxes, assurances et critères d’admissibilité varient selon la province et la municipalité et peuvent changer après notre date de révision.' },
    { question: 'Mes données sont-elles enregistrées ?', answer: 'Les calculs sont effectués dans votre navigateur. Un lien de partage inscrit les valeurs choisies dans l’URL.' },
  ],
  'fr-FR': [],
  'de-DE': [
    { question: 'Ist dies ein Kreditangebot?', answer: 'Nein. Es handelt sich um eine unverbindliche Beispielrechnung, nicht um ein Kreditangebot oder eine Steuer-, Rechts- oder Finanzberatung.' },
    { question: 'Was enthält die Monatsrate?', answer: 'Das Hauptergebnis umfasst Tilgung und Zinsen. Grunderwerbsteuer und weitere Kaufnebenkosten werden, soweit unterstützt, getrennt ausgewiesen.' },
    { question: 'Warum kann das Bankangebot abweichen?', answer: 'Banken können andere Zahlungstermine, Gebühren, Versicherungen, Zinssätze und Rundungsregeln verwenden. Bestätigen Sie die endgültigen Werte bei Ihrer Bank.' },
    { question: 'Was bewirken Sondertilgungen?', answer: 'Wenn der Vertrag sie erlaubt, können Sondertilgungen die Restschuld, die späteren Zinsen und die Laufzeit reduzieren. Prüfen Sie Grenzen und Vorfälligkeitskosten.' },
    { question: 'Unterscheiden sich lokale Steuern?', answer: 'Ja. Steuern, Versicherungen und Voraussetzungen unterscheiden sich nach Bundesland und können sich nach unserem Prüfdatum ändern.' },
    { question: 'Werden meine Rechnerdaten gespeichert?', answer: 'Die Berechnung erfolgt in Ihrem Browser. Ein Freigabelink enthält die ausgewählten Eingaben in der URL.' },
  ],
  'es-ES': [
    { question: '¿Es una oferta hipotecaria?', answer: 'No. Es una estimación orientativa, no una oferta de préstamo ni asesoramiento fiscal, jurídico o financiero.' },
    { question: '¿Qué incluye la cuota mensual?', answer: 'El resultado principal incluye capital e intereses. Los impuestos de transmisión y otros gastos de compra se muestran por separado cuando están disponibles.' },
    { question: '¿Por qué puede diferir la oferta del banco?', answer: 'Los prestamistas pueden usar otras fechas de pago, comisiones, seguros, tipos y reglas de redondeo. Confirma siempre las cifras definitivas con tu entidad.' },
    { question: '¿Cómo afectan los pagos adicionales?', answer: 'Si el contrato los permite, pueden reducir antes el capital, los intereses posteriores y el plazo. Comprueba los límites y posibles comisiones.' },
    { question: '¿Varían los impuestos locales?', answer: 'Sí. Los impuestos, seguros y requisitos dependen de la comunidad autónoma y pueden cambiar después de nuestra fecha de revisión.' },
    { question: '¿Se guardan los datos del cálculo?', answer: 'Los cálculos se realizan en tu navegador. Un enlace compartido incluye en la URL los valores seleccionados.' },
  ],
};

localeFaq['fr-FR'] = localeFaq['fr-CA'];
