import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { isLocaleSlug, localeBySlug, siteUrl, supportedLocaleSlugs } from '../../../../lib/seo';
import { taxSources } from '../../../../lib/taxes';

const publishedDate = '2026-08-25';

const articles = {
  amortization: { title: 'Mortgage amortization explained', description: 'A mortgage amortization schedule shows how each payment is split between interest, principal and the remaining balance.', body: ['An amortization schedule lists every planned payment. Each row shows the opening balance, interest for that period, principal repaid, any extra principal and the remaining balance. It is the clearest way to understand why a loan with the same monthly payment can have a very different interest cost when its term or rate changes.', 'For a fixed-rate repayment mortgage, interest is calculated from the balance at the start of a payment period. Early in the term, that balance is larger, so more of each scheduled payment goes to interest. As principal falls, the interest portion generally falls and the principal portion rises. The final payment is adjusted so the balance does not become negative.', 'Use the calculator schedule as an illustrative cash-flow model. Actual lender schedules can differ because of daily interest, payment dates, escrow, product fees, rate changes or contractual rounding.'] },
  'extra-payments': { title: 'How extra mortgage payments work', description: 'Extra principal payments can reduce total interest and shorten the payoff period when your loan terms allow them.', body: ['An extra mortgage payment is money applied directly to the outstanding principal after the scheduled payment. Reducing the balance earlier means later interest is calculated on a smaller amount. The calculator compares the same loan with and without a recurring monthly extra payment so the interest and time difference remains visible.', 'The effect is not guaranteed to match a lender statement. Some loans restrict overpayments, apply an annual limit, require a particular payment instruction or charge an early-repayment fee. An interest-only loan also has a principal balance due at the end of its term unless separate repayments are made.', 'Before paying extra, review your loan agreement and compare the expected interest saving with any fee, the value of maintaining emergency savings and other higher-cost debt.'] },
  affordability: { title: 'Mortgage affordability checklist', description: 'Mortgage affordability means testing the full housing budget, not only the principal-and-interest payment.', body: ['A mortgage payment estimate is only one part of affordability. A usable home-buying budget separates loan repayment from ownership costs and one-time transaction costs. The calculator deliberately keeps these categories separate so a property tax or transfer-tax estimate is not mistaken for interest owed to a lender.', 'Budget for recurring costs such as property tax, home insurance, flood cover where relevant, association or condominium charges, maintenance, utilities and a reserve for unexpected repairs. Also plan for the down payment, tax, legal or notary work, valuations, inspections, registration and lender fees where they apply.', 'This tool does not assess income, credit history, debt-to-income rules, stress tests or loan eligibility. Obtain a current lender quote and local professional advice before making a purchase decision.'] },
  methodology: { title: 'Mortgage calculation methodology', description: 'MortgageBreezy calculates fixed-rate payment illustrations and shows the applicable data version, rate convention and limits.', body: ['MortgageBreezy calculates a fixed-rate payment illustration from the loan amount, nominal annual rate, term, repayment type, payment frequency and optional extra principal. A repayment loan uses a standard amortization formula; with a zero rate, principal is divided evenly across the payment periods. Canada converts quoted rates using semi-annual compounding before calculating the selected payment frequency.', 'Every calculation retains precision internally and rounds currency only for display. The result page states the relevant calculation-data version, effective date, review date, included costs and exclusions. Transfer-tax and registration estimates are separate from the loan payment because they are generally transaction costs rather than recurring interest.', 'The calculator is not a lender underwriting system. It does not model variable-rate resets, lender-specific product pricing, all insurance premiums, daily-interest conventions, early-repayment penalties or every local registration fee. Confirm the current rule with the lender and the relevant public authority.'] },
  'legal-notice': { title: 'Legal notice', description: 'Legal information and disclaimer for the MortgageBreezy calculator.', body: ['MortgageBreezy provides educational estimates only. Nothing on this site is a loan offer, tax opinion, legal advice, financial advice or a recommendation to buy, sell or borrow.', 'Rates, tax rules, fees and eligibility can change. Confirm the current terms with your lender and the relevant authority, notary, conveyancer or qualified adviser before relying on an estimate.'] },
  privacy: { title: 'Privacy notice', description: 'How MortgageBreezy processes calculator inputs, share links and basic technical data.', body: ['Calculator inputs are processed in your browser to produce an estimate. MortgageBreezy does not require an account and the calculator does not ask for your name, address, income, bank details or other financial identity information.', 'When you create a share link, the selected loan amount, rate, term and related calculator settings are encoded in the URL. Anyone who receives that URL can read those values, so do not share a link containing inputs you consider private.', 'Our hosting provider may process standard technical logs needed to deliver and protect the site, such as the requested page, request time, IP address, browser information and error data. Retention and access are governed by the hosting provider and applicable law.', 'MortgageBreezy does not currently use advertising cookies or sell calculator inputs. If analytics, advertising or other optional tracking is introduced, this notice and any required consent controls will be updated before that tracking is enabled.', 'You can clear calculator values by resetting the form, removing the share parameters from the URL or closing the page. This notice was published and reviewed on 25 August 2026.'] },
} as const;
type ArticleSlug = keyof typeof articles;
function isArticleSlug(value: string): value is ArticleSlug { return value in articles; }
export function generateStaticParams() { return supportedLocaleSlugs.flatMap((locale) => Object.keys(articles).map((article) => ({ locale, article }))); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string; article: string }> }): Promise<Metadata> {
  const { locale, article } = await params;
  if (!isLocaleSlug(locale) || !isArticleSlug(article)) return {};
  const isPublishedEnglishGuide = locale === 'en-us';
  return { title: `${articles[article].title} | MortgageBreezy`, description: articles[article].description, alternates: { canonical: `${siteUrl}/${locale}/mortgage-calculator/${article}` }, robots: isPublishedEnglishGuide ? undefined : { index: false, follow: true } };
}
export default async function ArticlePage({ params }: { params: Promise<{ locale: string; article: string }> }) {
  const { locale, article } = await params;
  if (!isLocaleSlug(locale) || !isArticleSlug(article)) notFound();
  const page = articles[article]; const localeRoot = `/${locale}/mortgage-calculator`; const pageUrl = `${siteUrl}/${locale}/mortgage-calculator/${article}`;
  const structuredData = { '@context': 'https://schema.org', '@type': 'Article', headline: page.title, description: page.description, inLanguage: localeBySlug[locale], datePublished: publishedDate, dateModified: publishedDate, mainEntityOfPage: pageUrl, author: { '@type': 'Organization', name: 'MortgageBreezy Editorial Team', url: siteUrl }, publisher: { '@type': 'Organization', name: 'MortgageBreezy', url: siteUrl } };
  const officialSources = [taxSources.ukSdlt, taxSources.ontarioLtt, taxSources.germanyGrunderwerbsteuer, taxSources.franceDmto, taxSources.spainPropertyTaxes];
  return <main className="article-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} /><header className="site-header"><Link className="brand" href={localeRoot}>mortgage<span>breezy</span></Link><nav aria-label="Primary navigation"><Link href={localeRoot}>Calculator</Link><Link href={`${localeRoot}/methodology`}>Methodology</Link><Link href={`${localeRoot}/legal-notice`}>Legal notice</Link></nav></header><article><p className="eyebrow">{localeBySlug[locale]} · guide</p><h1>{page.title}</h1><p className="article-summary"><strong>Short answer:</strong> {page.description}</p>{page.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{article === 'methodology' && <section className="article-sources"><h2>Primary sources used for local-rule data</h2><ul>{officialSources.map((source) => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.name}</a> — effective {source.effectiveFrom}; reviewed {source.reviewedAt}.</li>)}</ul></section>}<section className="article-sources"><h2>Editorial and review policy</h2><p>MortgageBreezy maintains calculation-data versions and dates in the calculator. When a stable official formula is unavailable, the tool identifies the estimate as unavailable or requires user input instead of inventing a rate.</p></section><p className="article-meta">Published and reviewed: {publishedDate}</p><p><Link className="primary-button" href={localeRoot}>Open calculator</Link></p></article><footer className="site-footer"><span>© 2026 MortgageBreezy</span><Link href={`${localeRoot}/privacy`}>Privacy</Link><Link href={`${localeRoot}/legal-notice`}>Legal notice</Link></footer></main>;
}
