'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { jsPDF } from 'jspdf';
import { calculateMortgage, type CountryCode, type PaymentFrequency, type RepaymentType, usPmiEstimate } from '../lib/mortgage';
import { monthlyUsRecurringCosts, type UsLoanProgram, usLoanPrograms } from '../lib/us-costs';
import { amortizationCsv, decodeMortgageShare, encodeMortgageShare } from '../lib/export';
import { compareMortgageScenarios } from '../lib/compare';
import { calculationDataForCountry } from '../lib/calculation-data';
import { localeCopy, localeFaq } from '../lib/locales';
import { taxSources } from '../lib/taxes';
import { albertaLandTitlesTransferFee, britishColumbiaFirstTimeBuyerRefund, britishColumbiaNewHomeRefund, britishColumbiaPropertyTransferTax, canadaJurisdictions, canadaTransactionCostKind, franceDepartmentDmtoRate, franceDepartments, franceExistingHomeTransferTax, franceNewHomeTotalTax, germanTransferTax, manitobaLandTransferTax, newBrunswickRealPropertyTransferTax, newfoundlandDeedRegistrationFee, northwestTerritoriesLandTitleTransferFee, northwestTerritoriesMortgageRegistrationFee, novaScotiaMunicipalDeedTransferTax, novaScotiaMunicipalities, novaScotiaNonResidentDeedTransferTax, ontarioFirstTimeBuyerRefund, ontarioLandTransferTax, ontarioNonResidentSpeculationTax, princeEdwardIslandRealPropertyTransferTax, quebecImmovableTransferDuties, saskatchewanLandRegistryTransferFee, scotlandLbtt, spainAutonomousCommunities, spainItpGeneralRate, spainUsedHomeItpWithProfile, spainNewHomeTotalTax, spainReducedItpRules, torontoFirstTimeBuyerRefund, torontoMunicipalLandTransferTax, torontoMunicipalNonResidentSpeculationTax, ukSdlt, walesLtt, yukonLandTitleTransferFee, yukonMortgageRegistrationFee } from '../lib/taxes';

export type Locale = 'en-US' | 'en-GB' | 'en-CA' | 'fr-CA' | 'de-DE' | 'fr-FR' | 'es-ES';
const locales: Array<[Locale, string, CountryCode]> = [['en-US', 'United States', 'US'], ['en-GB', 'United Kingdom', 'GB'], ['en-CA', 'Canada', 'CA'], ['fr-CA', 'Canada, français', 'CA'], ['de-DE', 'Deutschland', 'DE'], ['fr-FR', 'France', 'FR'], ['es-ES', 'España', 'ES']];
const currency: Record<CountryCode, string> = { US: 'USD', GB: 'GBP', CA: 'CAD', DE: 'EUR', FR: 'EUR', ES: 'EUR' };
const localeCountry: Record<string, CountryCode> = { 'en-us': 'US', 'en-gb': 'GB', 'en-ca': 'CA', 'fr-ca': 'CA', 'de-de': 'DE', 'fr-fr': 'FR', 'es-es': 'ES' };

function money(value: number, locale: Locale, country: CountryCode) { return new Intl.NumberFormat(locale, { style: 'currency', currency: currency[country], maximumFractionDigits: 0 }).format(value); }

export default function MortgageCalculator({ locale = 'en-US' }: { locale?: Locale }) {
  const copy = localeCopy[locale];
  const country = localeCountry[locale.toLowerCase()] ?? locales.find(([value]) => value === locale)?.[2] ?? 'US';
  const [loanAmount, setLoanAmount] = useState(360000); const [annualRate, setAnnualRate] = useState(6.25); const [termYears, setTermYears] = useState(30); const [extraMonthly, setExtraMonthly] = useState(0); const [propertyValue, setPropertyValue] = useState(450000); const [annualMortgageInsurance, setAnnualMortgageInsurance] = useState(0); const [fixedPeriodYears, setFixedPeriodYears] = useState(country === 'DE' || country === 'CA' ? 5 : 0); const [repaymentType, setRepaymentType] = useState<RepaymentType>('repayment'); const [frequency, setFrequency] = useState<PaymentFrequency>('monthly'); const [taxResidence, setTaxResidence] = useState('England / Northern Ireland'); const [germanState, setGermanState] = useState('Bayern'); const [canadaProvince, setCanadaProvince] = useState('ON'); const [canadaAssessedValue, setCanadaAssessedValue] = useState(450000); const [canadaNonResident, setCanadaNonResident] = useState(false); const [torontoProperty, setTorontoProperty] = useState(false); const [novaScotiaMunicipality, setNovaScotiaMunicipality] = useState('Halifax Regional Municipality'); const [frenchDepartment, setFrenchDepartment] = useState('Ain'); const [spanishHomeType, setSpanishHomeType] = useState('used'); const [spanishCommunity, setSpanishCommunity] = useState('Andalucía'); const [spainHabitual, setSpainHabitual] = useState(false); const [spainFirstHome, setSpainFirstHome] = useState(false); const [spainUnder35, setSpainUnder35] = useState(false); const [spainDisabled, setSpainDisabled] = useState(false); const [spainLargeFamily, setSpainLargeFamily] = useState(false); const [spainProtectedHousing, setSpainProtectedHousing] = useState(false); const [usLoanProgram, setUsLoanProgram] = useState<UsLoanProgram>('conventional'); const [usAnnualPropertyTax, setUsAnnualPropertyTax] = useState(0); const [usAnnualHomeInsurance, setUsAnnualHomeInsurance] = useState(0); const [usMonthlyHoa, setUsMonthlyHoa] = useState(0); const [usAnnualFloodInsurance, setUsAnnualFloodInsurance] = useState(0);
  const [franceFirstTimeBuyer, setFranceFirstTimeBuyer] = useState(false);
  const [ukFirstTimeBuyer, setUkFirstTimeBuyer] = useState(false); const [ukAdditionalProperty, setUkAdditionalProperty] = useState(false); const [ukNonResident, setUkNonResident] = useState(false); const [canadaFirstTimeBuyer, setCanadaFirstTimeBuyer] = useState(false);
  const [germanExemptRelationship, setGermanExemptRelationship] = useState(false); const [canadaNewBuild, setCanadaNewBuild] = useState(false);
  const [showFullSchedule, setShowFullSchedule] = useState(false);
  const [comparisonExtraMonthly, setComparisonExtraMonthly] = useState(300);
  useEffect(() => { document.documentElement.lang = locale; const timer = window.setTimeout(() => { const value = new URLSearchParams(window.location.search).get('share'); if (!value) return; const shared = decodeMortgageShare(value); if (!shared || shared.country !== country) return; setLoanAmount(shared.loanAmount); setAnnualRate(shared.annualRate); setTermYears(shared.termYears); setExtraMonthly(shared.extraMonthly); setPropertyValue(shared.propertyValue ?? 450000); setAnnualMortgageInsurance(shared.annualMortgageInsurance ?? 0); setFixedPeriodYears(shared.fixedPeriodYears ?? 0); setRepaymentType(shared.repaymentType ?? 'repayment'); setFrequency(shared.paymentFrequency ?? 'monthly'); }, 0); return () => window.clearTimeout(timer); }, [country, locale]);
  const result = useMemo(() => calculateMortgage({ country, loanAmount, annualRate, termYears, extraMonthly, propertyValue, annualMortgageInsurance, fixedPeriodYears, repaymentType, paymentFrequency: frequency }), [country, loanAmount, annualRate, termYears, extraMonthly, propertyValue, annualMortgageInsurance, fixedPeriodYears, repaymentType, frequency]);
  const comparison = useMemo(() => compareMortgageScenarios([{ name: 'Base plan', country, loanAmount, annualRate, termYears, extraMonthly: 0, propertyValue, annualMortgageInsurance, fixedPeriodYears, repaymentType, paymentFrequency: frequency }, { name: `+${comparisonExtraMonthly}/month`, country, loanAmount, annualRate, termYears, extraMonthly: comparisonExtraMonthly, propertyValue, annualMortgageInsurance, fixedPeriodYears, repaymentType, paymentFrequency: frequency }]), [country, loanAmount, annualRate, termYears, comparisonExtraMonthly, propertyValue, annualMortgageInsurance, fixedPeriodYears, repaymentType, frequency]);
  const novaScotiaRate = novaScotiaMunicipalities.find(([name]) => name === novaScotiaMunicipality)?.[1] ?? 0;
  const canadaCostKind = canadaTransactionCostKind(canadaProvince);
  const calculationData = calculationDataForCountry(country);
  const source = country === 'GB' ? taxSources.ukSdlt : country === 'CA' ? ({ AB: taxSources.albertaLandTitlesFees, NL: taxSources.newfoundlandDeedsFees, SK: taxSources.saskatchewanLandRegistryFees, YT: taxSources.yukonLandTitlesFees, NT: taxSources.northwestTerritoriesLandTitlesFees, ON: taxSources.ontarioLtt, QC: taxSources.quebecDuties, NB: taxSources.newBrunswickRPTT, PE: taxSources.peiRPTT, NS: taxSources.novaScotiaMunicipalDTT }[canadaProvince]) : country === 'DE' ? taxSources.germanyGrunderwerbsteuer : country === 'FR' ? taxSources.franceDmto : country === 'ES' ? taxSources.spainPropertyTaxes : undefined;
  const taxEstimate = country === 'GB' ? (taxResidence === 'Scotland' ? scotlandLbtt(propertyValue, ukFirstTimeBuyer, ukAdditionalProperty) : taxResidence === 'Wales' ? walesLtt(propertyValue, ukAdditionalProperty) : ukSdlt(propertyValue, { firstTimeBuyer: ukFirstTimeBuyer, additionalProperty: ukAdditionalProperty, nonUkResident: ukNonResident })) : country === 'CA' ? (canadaProvince === 'AB' ? albertaLandTitlesTransferFee(propertyValue) + albertaLandTitlesTransferFee(loanAmount) : canadaProvince === 'NL' ? newfoundlandDeedRegistrationFee(propertyValue) + newfoundlandDeedRegistrationFee(loanAmount) : canadaProvince === 'ON' ? ontarioLandTransferTax(propertyValue) - ontarioFirstTimeBuyerRefund(ontarioLandTransferTax(propertyValue), canadaFirstTimeBuyer) + (torontoProperty ? torontoMunicipalLandTransferTax(propertyValue) - torontoFirstTimeBuyerRefund(torontoMunicipalLandTransferTax(propertyValue), canadaFirstTimeBuyer) + torontoMunicipalNonResidentSpeculationTax(propertyValue, canadaNonResident) : 0) + ontarioNonResidentSpeculationTax(propertyValue, canadaNonResident) : canadaProvince === 'BC' ? britishColumbiaPropertyTransferTax(propertyValue) - britishColumbiaFirstTimeBuyerRefund(propertyValue, canadaFirstTimeBuyer) - britishColumbiaNewHomeRefund(propertyValue, canadaNewBuild) : canadaProvince === 'MB' ? manitobaLandTransferTax(propertyValue) : canadaProvince === 'QC' ? quebecImmovableTransferDuties(propertyValue) : canadaProvince === 'NB' ? newBrunswickRealPropertyTransferTax(propertyValue, canadaAssessedValue) : canadaProvince === 'PE' ? princeEdwardIslandRealPropertyTransferTax(propertyValue, canadaAssessedValue) : canadaProvince === 'NS' ? novaScotiaMunicipalDeedTransferTax(propertyValue, novaScotiaRate, canadaAssessedValue) + (canadaNonResident ? novaScotiaNonResidentDeedTransferTax(propertyValue, canadaAssessedValue) : 0) : canadaProvince === 'YT' ? yukonLandTitleTransferFee(propertyValue) + yukonMortgageRegistrationFee(loanAmount) : canadaProvince === 'NT' ? northwestTerritoriesLandTitleTransferFee(propertyValue) + northwestTerritoriesMortgageRegistrationFee(loanAmount) : canadaProvince === 'SK' ? saskatchewanLandRegistryTransferFee(propertyValue) : 0) : country === 'DE' ? germanTransferTax(propertyValue, germanState, germanExemptRelationship) : country === 'FR' ? (spanishHomeType === 'new' ? franceNewHomeTotalTax(propertyValue) : franceExistingHomeTransferTax(propertyValue, franceDepartmentDmtoRate[frenchDepartment] ?? 0.05, franceFirstTimeBuyer)) : country === 'ES' ? (spanishHomeType === 'new' ? spainNewHomeTotalTax(propertyValue, spanishCommunity, spainProtectedHousing) : spainUsedHomeItpWithProfile(propertyValue, spanishCommunity, { habitualResidence: spainHabitual, firstHome: spainFirstHome, under35: spainUnder35, disabled: spainDisabled, largeFamily: spainLargeFamily, protectedHousing: spainProtectedHousing })) : 0;
  const pmiEstimate = country === 'US' ? usPmiEstimate(propertyValue, loanAmount) : 0;
  const activeTaxSource = source;
  const localRuleSelection = country === 'GB' ? taxResidence : country === 'CA' ? canadaJurisdictions.find((province) => province.code === canadaProvince)?.name ?? canadaProvince : country === 'DE' ? germanState : country === 'FR' ? frenchDepartment : country === 'ES' ? spanishCommunity : 'United States';
  const usRecurringCosts = country === 'US' ? monthlyUsRecurringCosts({ annualPropertyTax: usAnnualPropertyTax, annualHomeInsurance: usAnnualHomeInsurance, monthlyHoa: usMonthlyHoa, annualFloodInsurance: usAnnualFloodInsurance }) : 0;
  const reset = () => { setLoanAmount(360000); setAnnualRate(6.25); setTermYears(30); setExtraMonthly(0); setPropertyValue(450000); setAnnualMortgageInsurance(0); setRepaymentType('repayment'); setFrequency('monthly'); };
  const shareInputs = { country, loanAmount, annualRate, termYears, extraMonthly, propertyValue, annualMortgageInsurance, fixedPeriodYears, repaymentType, paymentFrequency: frequency } as const;
  const downloadCsv = () => { const blob = new Blob([amortizationCsv(result.schedule)], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'mortgage-amortization.csv'; anchor.click(); URL.revokeObjectURL(url); };
  const shareEstimate = async () => { const url = `${window.location.origin}${window.location.pathname}?share=${encodeURIComponent(encodeMortgageShare(shareInputs))}`; try { await navigator.clipboard?.writeText(url); } catch { /* Sharing must still work where clipboard permission is denied. */ } window.history.replaceState({}, '', url); };
  const downloadPdf = () => {
    const pdf = new jsPDF({ unit: 'pt', format: 'a4' });
    const rows = [
      ['Monthly payment', money(result.monthlyPayment + usRecurringCosts, locale, country)],
      ['Total interest', money(result.totalInterest, locale, country)],
      [`Total paid over ${termYears} years`, money(result.totalPaid, locale, country)],
      ['Payoff time', `${Math.floor(result.payoffMonths / 12)}y ${result.payoffMonths % 12}m`],
      ['Transaction cost estimate', taxEstimate > 0 ? money(taxEstimate, locale, country) : 'Not included'],
      ['Calculation data', `${calculationData.version} | effective ${calculationData.effectiveFrom} | reviewed ${calculationData.reviewedAt}`],
    ];
    pdf.setFillColor(232, 238, 231); pdf.rect(0, 0, 595, 94, 'F');
    pdf.setTextColor(29, 39, 34); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(22); pdf.text('Clear Mortgage Estimate', 42, 52);
    pdf.setFont('helvetica', 'normal'); pdf.setFontSize(10); pdf.text(`${locale} | generated ${new Date().toLocaleDateString(locale)}`, 42, 72);
    let y = 132; pdf.setFontSize(13); pdf.setFont('helvetica', 'bold'); pdf.text('Estimate summary', 42, y); y += 24;
    pdf.setFontSize(10); pdf.setFont('helvetica', 'normal');
    for (const [label, value] of rows) { pdf.setTextColor(90, 102, 95); pdf.text(label, 42, y); pdf.setTextColor(29, 39, 34); pdf.setFont('helvetica', 'bold'); pdf.text(value, 553, y, { align: 'right' }); pdf.setFont('helvetica', 'normal'); y += 24; }
    y += 16; pdf.setFont('helvetica', 'bold'); pdf.setFontSize(13); pdf.text('Inputs and assumptions', 42, y); y += 22;
    pdf.setFont('helvetica', 'normal'); pdf.setFontSize(9); const details = [
      `Loan amount: ${money(loanAmount, locale, country)} | Annual rate: ${annualRate}% | Term: ${termYears} years`,
      `Repayment type: ${repaymentType} | Extra payment: ${money(extraMonthly, locale, country)} per month`,
      `Formula: ${calculationData.formula}`,
      `Included: ${calculationData.included}`,
      `Excluded: ${calculationData.excluded}`,
      'Educational estimate only. It is not a loan offer, tax opinion, legal advice or financial advice.',
    ];
    for (const detail of details) { const lines = pdf.splitTextToSize(detail, 511); pdf.text(lines, 42, y); y += lines.length * 14 + 5; }
    pdf.save('mortgage-estimate.pdf');
  };

  return <main lang={locale}>
    <header className="site-header"><Link className="brand" href="/">mortgage<span>breezy</span></Link><nav aria-label="Primary navigation"><a href="#calculator">{copy.calculator}</a><a href="#methodology">{copy.methodology}</a><a href="#local-rules">{copy.localRules}</a></nav><label className="locale-select"><span className="sr-only">Choose country</span><select value={locale} onChange={(event) => { const next = event.target.value.toLowerCase(); window.location.href = next === 'en-us' ? '/' : `/${next}/mortgage-calculator`; }}>{locales.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label></header>
    <section className="intro"><div><p className="eyebrow">{locale} · {copy.localRules}</p><h1>{copy.monthlyPayment}</h1><p className="lede">{copy.principalInterest}</p></div><p className="review-note"><strong>{copy.methodology}</strong><br />{country === 'CA' ? 'Canadian semi-annual compounding with your selected payment frequency.' : country === 'GB' ? 'Repayment estimate with SDLT shown separately for England and Northern Ireland.' : country === 'DE' ? 'Annuité estimate with the remaining balance shown at the end of the fixed period.' : 'Fixed-rate estimate with the local currency and cost categories shown separately.'}</p></section>
    <section id="calculator" className="calculator-layout" aria-label="Mortgage calculator"><form className="input-panel" onSubmit={(event) => event.preventDefault()}><div className="panel-heading"><div><p className="eyebrow">Your loan</p><h2>Set your starting numbers</h2></div><span className="step-mark">Live estimate</span></div><div className="field-grid">
      <label className="field"><span>{copy.loanAmount ?? 'Loan amount'}</span><div className="input-wrap"><span>{currency[country] === 'EUR' ? '€' : currency[country] === 'GBP' ? '£' : '$'}</span><input type="number" min="1" step="1000" value={loanAmount} onChange={(e) => setLoanAmount(Number(e.target.value))} /></div><small>Amount borrowed after your down payment</small></label>
      <label className="field"><span>{copy.interestRate ?? 'Interest rate'}</span><div className="input-wrap"><input type="number" min="0" step="0.01" value={annualRate} onChange={(e) => setAnnualRate(Number(e.target.value))} /><span>%</span></div><small>{country === 'CA' ? 'Quoted annual rate, compounded semi-annually' : 'Annual nominal rate'}</small></label>
      <label className="field"><span>{copy.term ?? 'Amortization term'}</span><div className="input-wrap"><input type="number" min="1" max="50" step="1" value={termYears} onChange={(e) => setTermYears(Number(e.target.value))} /><span>years</span></div><small>Total time to repay the balance</small></label>
      <label className="field"><span>{copy.extraPayment ?? 'Extra payment each month'}</span><div className="input-wrap"><span>{currency[country] === 'EUR' ? '€' : currency[country] === 'GBP' ? '£' : '$'}</span><input type="number" min="0" step="50" value={extraMonthly} onChange={(e) => setExtraMonthly(Number(e.target.value))} /></div><small>Applied directly to principal</small></label>
      <label className="field"><span>{copy.repaymentType ?? 'Repayment type'}</span><select className="full-select" value={repaymentType} onChange={(e) => setRepaymentType(e.target.value as RepaymentType)}><option value="repayment">Repayment mortgage</option><option value="interest-only">Interest-only</option></select><small>Interest-only leaves the principal due at term end</small></label>
      {country === 'CA' && <label className="field"><span>Payment frequency</span><select className="full-select" value={frequency} onChange={(e) => setFrequency(e.target.value as PaymentFrequency)}><option value="monthly">Monthly</option><option value="semi-monthly">Semi-monthly</option><option value="biweekly">Biweekly</option><option value="accelerated-biweekly">Accelerated biweekly</option><option value="weekly">Weekly</option><option value="accelerated-weekly">Accelerated weekly</option></select><small>Accelerated schedules equal one extra monthly payment per year</small></label>}
      {(country === 'DE' || country === 'CA') && <label className="field"><span>Fixed-rate period</span><div className="input-wrap"><input type="number" min="1" max={termYears} step="1" value={fixedPeriodYears} onChange={(e) => setFixedPeriodYears(Number(e.target.value))} /><span>years</span></div><small>Remaining balance is shown at this point</small></label>}
      {country === 'US' && <><label className="field"><span>Property value</span><div className="input-wrap"><span>$</span><input type="number" min="1" step="1000" value={propertyValue} onChange={(e) => setPropertyValue(Number(e.target.value))} /></div><small>Used to estimate PMI when LTV is above 80%</small></label><label className="field"><span>Loan program</span><select className="full-select" value={usLoanProgram} onChange={(e) => setUsLoanProgram(e.target.value as UsLoanProgram)}>{Object.entries(usLoanPrograms).map(([value, program]) => <option value={value} key={value}>{program.label}</option>)}</select><small>{usLoanPrograms[usLoanProgram].note}</small></label><label className="field"><span>Annual property tax</span><div className="input-wrap"><span>$</span><input type="number" min="0" step="100" value={usAnnualPropertyTax} onChange={(e) => setUsAnnualPropertyTax(Number(e.target.value))} /></div><small>Enter the local assessor bill; no national rate is assumed</small></label><label className="field"><span>Annual homeowners insurance</span><div className="input-wrap"><span>$</span><input type="number" min="0" step="100" value={usAnnualHomeInsurance} onChange={(e) => setUsAnnualHomeInsurance(Number(e.target.value))} /></div></label><label className="field"><span>Annual flood insurance</span><div className="input-wrap"><span>$</span><input type="number" min="0" step="100" value={usAnnualFloodInsurance} onChange={(e) => setUsAnnualFloodInsurance(Number(e.target.value))} /></div></label><label className="field"><span>Monthly HOA</span><div className="input-wrap"><span>$</span><input type="number" min="0" step="25" value={usMonthlyHoa} onChange={(e) => setUsMonthlyHoa(Number(e.target.value))} /></div></label></>}
      {country === 'GB' && <label className="field"><span>Transaction tax area</span><select className="full-select" value={taxResidence} onChange={(e) => setTaxResidence(e.target.value)}><option>England / Northern Ireland</option><option>Scotland</option><option>Wales</option></select><small>Scotland and Wales use separate tax systems</small></label>}
      {country === 'GB' && <><label className="check-row"><input type="checkbox" checked={ukFirstTimeBuyer} onChange={(e) => setUkFirstTimeBuyer(e.target.checked)} /><span>First-time buyer</span></label><label className="check-row"><input type="checkbox" checked={ukAdditionalProperty} onChange={(e) => setUkAdditionalProperty(e.target.checked)} /><span>Additional property / second home</span></label><label className="check-row"><input type="checkbox" checked={ukNonResident} onChange={(e) => setUkNonResident(e.target.checked)} /><span>Non-UK resident (England / Northern Ireland SDLT surcharge)</span></label></>}
      {country === 'CA' && <><label className="field"><span>Province tax dataset</span><select className="full-select" value={canadaProvince} onChange={(e) => setCanadaProvince(e.target.value)}>{canadaJurisdictions.map((province) => <option value={province.code} key={province.code}>{province.name}{province.status === 'manual-verification-required' ? ' (manual verification required)' : ''}</option>)}</select><small>{canadaProvince === 'ON' ? 'Ontario provincial land transfer tax' : canadaProvince === 'NS' ? 'Nova Scotia municipal deed transfer tax is selected from the official July 2026 municipality table.' : canadaCostKind === 'registration-fees' ? 'This jurisdiction uses official land-title or registry fees, not a land-transfer tax.' : canadaCostKind === 'manual-verification-required' ? 'Nunavut registration costs are not estimated: the supported official source has no stable formula. Confirm charges with the Land Titles Office.' : 'Calculation uses the official provincial transfer-tax rule where implemented.'}</small></label>{canadaProvince === 'ON' && <><label className="check-row"><input type="checkbox" checked={torontoProperty} onChange={(e) => setTorontoProperty(e.target.checked)} /><span>Property is in Toronto (add official MLTT)</span></label><label className="check-row"><input type="checkbox" checked={canadaNonResident} onChange={(e) => setCanadaNonResident(e.target.checked)} /><span>Foreign buyer / non-resident (Ontario NRST 25%; Toronto MNRST 10% if applicable)</span></label></>}{canadaProvince === 'NS' && <label className="field"><span>Nova Scotia municipality</span><select className="full-select" value={novaScotiaMunicipality} onChange={(e) => setNovaScotiaMunicipality(e.target.value)}>{novaScotiaMunicipalities.map(([name, rate]) => <option value={name} key={name}>{name} ({rate * 100}%)</option>)}</select></label>}{(canadaProvince === 'NB' || canadaProvince === 'PE' || canadaProvince === 'NS') && <label className="field"><span>Assessed value (CAD)</span><input type="number" value={canadaAssessedValue} onChange={(e) => setCanadaAssessedValue(Number(e.target.value))} /></label>}{canadaProvince === 'NS' && <label className="check-row"><input type="checkbox" checked={canadaNonResident} onChange={(e) => setCanadaNonResident(e.target.checked)} /><span>Non-resident residential purchaser (10% provincial PDTT)</span></label>}</>}
      {country === 'CA' && (canadaProvince === 'ON' || canadaProvince === 'BC') && <label className="check-row"><input type="checkbox" checked={canadaFirstTimeBuyer} onChange={(e) => setCanadaFirstTimeBuyer(e.target.checked)} /><span>First-time homebuyer (Ontario refund up to CAD 4,000; Toronto municipal refund up to CAD 4,475; BC exemption/partial exemption up to CAD 860,000)</span></label>}
      {country === 'CA' && canadaProvince === 'BC' && <label className="check-row"><input type="checkbox" checked={canadaNewBuild} onChange={(e) => setCanadaNewBuild(e.target.checked)} /><span>Qualifying newly built principal residence (BC exemption up to CAD 1.1M; phase-out to CAD 1.15M)</span></label>}
      {country === 'DE' && <label className="check-row"><input type="checkbox" checked={germanExemptRelationship} onChange={(e) => setGermanExemptRelationship(e.target.checked)} /><span>Transfer between spouse/registered partner or direct-line relatives (statutory exemption; not a normal purchase)</span></label>}
      {country === 'DE' && <label className="field"><span>Bundesland</span><select className="full-select" value={germanState} onChange={(e) => setGermanState(e.target.value)}>{Object.keys({ 'Baden-Württemberg': 1, Bayern: 1, Berlin: 1, Brandenburg: 1, Bremen: 1, Hamburg: 1, Hessen: 1, 'Mecklenburg-Vorpommern': 1, Niedersachsen: 1, 'Nordrhein-Westfalen': 1, 'Rheinland-Pfalz': 1, Saarland: 1, Sachsen: 1, 'Sachsen-Anhalt': 1, 'Schleswig-Holstein': 1, Thüringen: 1 }).map((state) => <option key={state}>{state}</option>)}</select><small>Grunderwerbsteuer rate varies by state</small></label>}
      {(country === 'FR' || country === 'ES') && <label className="field"><span>Property type</span><select className="full-select" value={spanishHomeType} onChange={(e) => setSpanishHomeType(e.target.value)}><option value="used">Existing home</option><option value="new">New home</option></select><small>New and existing homes use different tax systems</small></label>}
      {country === 'FR' && <label className="field"><span>Département</span><select className="full-select" value={frenchDepartment} onChange={(e) => setFrenchDepartment(e.target.value)}>{franceDepartments.map((department) => <option key={department}>{department}</option>)}</select><small>Official rate must be checked for the deed date</small></label>}
      {country === 'FR' && spanishHomeType === 'used' && <label className="check-row"><input type="checkbox" checked={franceFirstTimeBuyer} onChange={(e) => setFranceFirstTimeBuyer(e.target.checked)} /><span>First-time buyer and main residence (temporary DMTO increase excluded)</span></label>}
      {country === 'FR' && spanishHomeType === 'used' && <p className="field-note">Official DMTO department rate: {((franceDepartmentDmtoRate[frenchDepartment] ?? 0.05) * 100).toFixed(1)}% · Source: French tax administration table dated 1 June 2026</p>}
      {country === 'ES' && <label className="field"><span>Autonomous community</span><select className="full-select" value={spanishCommunity} onChange={(e) => setSpanishCommunity(e.target.value)}>{spainAutonomousCommunities.map((community) => <option key={community}>{community}</option>)}</select><small>ITP/AJD rates and reliefs are set by the autonomous community</small></label>}
      {country === 'ES' && <><label className="check-row"><input type="checkbox" checked={spainHabitual} onChange={(e) => setSpainHabitual(e.target.checked)} /><span>Property will be my habitual residence</span></label><label className="check-row"><input type="checkbox" checked={spainFirstHome} onChange={(e) => setSpainFirstHome(e.target.checked)} /><span>First home</span></label><label className="check-row"><input type="checkbox" checked={spainUnder35} onChange={(e) => setSpainUnder35(e.target.checked)} /><span>Buyer is under 35</span></label><label className="check-row"><input type="checkbox" checked={spainDisabled} onChange={(e) => setSpainDisabled(e.target.checked)} /><span>Buyer has an officially recognised disability</span></label><label className="check-row"><input type="checkbox" checked={spainLargeFamily} onChange={(e) => setSpainLargeFamily(e.target.checked)} /><span>Large-family status</span></label><label className="check-row"><input type="checkbox" checked={spainProtectedHousing} onChange={(e) => setSpainProtectedHousing(e.target.checked)} /><span>Protected housing</span></label></>}
      {country === 'ES' && spanishHomeType === 'used' && <p className="field-note">Official general ITP rate: {((spainItpGeneralRate[spanishCommunity] ?? 0.06) * 100).toFixed(1)}% · Reduced rates and value bands require separate eligibility inputs.</p>}
      {country === 'ES' && <p className="field-note">Official relief summary: {spainReducedItpRules[spanishCommunity] ?? 'No reduced-rate summary is currently encoded; verify the deed date and buyer eligibility with the regional authority.'}</p>}
    </div><div className="assumption"><span className="assumption-icon" aria-hidden="true">i</span><p>Rules marked as estimates are separate from the loan payment. Confirm the lender quote, tax authority, and contract before making a decision.</p></div><button className="secondary-button" type="button" onClick={reset}>Reset inputs</button></form>
      <aside className="result-panel" aria-live="polite"><div className="result-top"><p className="eyebrow">Estimated monthly payment</p><div className="hero-number">{money(result.monthlyPayment + usRecurringCosts, locale, country)}</div><p className="result-subtitle">{repaymentType === 'interest-only' ? 'Interest only, principal remains due' : 'Principal and interest, before recurring property costs'}</p></div><div className="result-list"><div><span>Total interest</span><strong>{money(result.totalInterest, locale, country)}</strong></div><div><span>Total paid over {termYears} years</span><strong>{money(result.totalPaid, locale, country)}</strong></div><div><span>Payoff time</span><strong>{Math.floor(result.payoffMonths / 12)}y {result.payoffMonths % 12}m</strong></div>{result.balanceAtFixedPeriodEnd !== undefined && <div><span>Balance after fixed period</span><strong>{money(result.balanceAtFixedPeriodEnd, locale, country)}</strong></div>}{taxEstimate > 0 && <div><span>{country === 'CA' && canadaCostKind === 'registration-fees' ? 'Land-title / registry fees' : 'Property transfer tax'}</span><strong>{money(taxEstimate, locale, country)}</strong></div>}{country === 'CA' && canadaCostKind === 'manual-verification-required' && <div><span>Registration costs</span><strong>Not estimated</strong></div>}{pmiEstimate > 0 && <div><span>Estimated PMI / month</span><strong>{money(pmiEstimate, locale, country)}</strong></div>}</div><div className="savings-box"><div><span>Interest saved</span><strong>{money(result.interestSaved, locale, country)}</strong></div><div><span>Time saved</span><strong>{result.monthsSaved} months</strong></div></div><div className="result-actions"><button className="primary-button" type="button" onClick={downloadCsv}>Download amortization CSV</button><button className="text-button" type="button" onClick={downloadPdf}>Download PDF estimate</button><button className="text-button" type="button" onClick={shareEstimate}>Copy share link <span aria-hidden="true">↗</span></button></div></aside></section>
    <section className="below-grid" id="methodology"><div><p className="eyebrow">How to read this</p><h2>A payment is only one part of the decision.</h2><p>The first years of a mortgage usually carry more interest than principal. The local rules panel keeps taxes, insurance, and market conventions separate so you can see what is assumed.</p><a className="inline-link" href="#schedule">View the amortization table <span aria-hidden="true">→</span></a></div><div className="mini-breakdown"><div className="breakdown-bar"><span style={{ width: `${Math.max(10, Math.min(90, loanAmount / (loanAmount + result.totalInterest) * 100))}%` }} /><span /></div><div className="legend"><span><i className="legend-principal" />Principal</span><strong>{money(loanAmount, locale, country)}</strong><span><i className="legend-interest" />Interest</span><strong>{money(result.totalInterest, locale, country)}</strong></div></div></section>
    <section className="comparison-card"><div className="schedule-heading"><div><p className="eyebrow">Compare plans</p><h2>See the cost of paying extra</h2></div><label className="comparison-input"><span>Extra monthly payment</span><input type="number" min="0" step="50" value={comparisonExtraMonthly} onChange={(event) => setComparisonExtraMonthly(Number(event.target.value))} /></label></div><div className="table-scroll"><table><thead><tr><th>Scenario</th><th>Total interest</th><th>Payoff time</th><th>Interest saved</th></tr></thead><tbody>{comparison.map(({ name, result: scenario }) => <tr key={name}><td>{name}</td><td>{money(scenario.totalInterest, locale, country)}</td><td>{Math.floor(scenario.payoffMonths / 12)}y {scenario.payoffMonths % 12}m</td><td>{money(Math.max(0, comparison[0].result.totalInterest - scenario.totalInterest), locale, country)}</td></tr>)}</tbody></table></div></section>
    <section className="schedule-preview" id="schedule"><div className="schedule-heading"><div><p className="eyebrow">{showFullSchedule ? 'Complete schedule' : 'First six periods'}</p><h2>Amortization preview</h2></div><button className="text-button" type="button" onClick={() => setShowFullSchedule((value) => !value)}>{showFullSchedule ? 'Show first six' : 'See full schedule'} <span aria-hidden="true">→</span></button></div><div className="table-scroll"><table><thead><tr><th>Period</th><th>Payment</th><th>Principal</th><th>Interest</th><th>Balance</th></tr></thead><tbody>{result.schedule.slice(0, showFullSchedule ? result.schedule.length : 6).map((row) => <tr key={row.period}><td>{row.period}</td><td>{money(row.payment, locale, country)}</td><td>{money(row.principal, locale, country)}</td><td>{money(row.interest, locale, country)}</td><td>{money(row.balance, locale, country)}</td></tr>)}</tbody></table></div></section>
    <section className="source-card" id="sources"><div><p className="eyebrow">Sources and assumptions</p><h2>Transparent by design.</h2><p>Loan payment uses the selected country compounding convention. Taxes and recurring costs are separate estimates; local rates, insurance quotes, closing costs and lender fees may not be included.</p></div><div><p><strong>Calculation data:</strong> {calculationData.version} · effective from {calculationData.effectiveFrom} · reviewed {calculationData.reviewedAt}.</p><p className="field-note"><strong>Applies to:</strong> {calculationData.applicability}<br /><strong>Formula:</strong> {calculationData.formula}<br /><strong>Rounding:</strong> {calculationData.rounding}<br /><strong>Included:</strong> {calculationData.included}<br /><strong>Excluded:</strong> {calculationData.excluded}</p><p><strong>Official source:</strong> {source ? source.name : country === 'CA' && canadaCostKind === 'manual-verification-required' ? 'Nunavut registry charges require direct confirmation; no formula is applied.' : 'Local property tax and insurance are user-entered estimates.'}</p>{source && <p><a className="inline-link" href={source.url} target="_blank" rel="noreferrer">Open official source ↗</a><br /><small>Effective from {source.effectiveFrom}; reviewed {source.reviewedAt}.</small></p>}<p className="field-note">This calculator is educational only and is not a loan offer, tax opinion, legal advice or financial advice. Confirm the current rule with the lender, tax authority, notary or conveyancer before relying on it.</p></div></section>
    <section className="methodology" id="local-rules"><div><p className="eyebrow">Methodology and local rules</p><h2>Built to explain the assumptions.</h2></div><div><p>{localRuleSelection} is selected for the transaction-tax context. {country === 'CA' ? 'Canada uses a semi-annual compounding conversion for the quoted rate.' : 'The displayed loan uses the local currency and separates loan repayment from transaction costs.'} Country rules are versioned and should be checked against the lender and authority at the time of purchase.</p>{activeTaxSource && <p className="field-note">Source: <a href={activeTaxSource.url} target="_blank" rel="noreferrer">{activeTaxSource.name}</a> · Effective from {activeTaxSource.effectiveFrom} · Reviewed {activeTaxSource.reviewedAt}. This is an estimate; confirm the deed date, eligibility, lender terms and local authority before relying on it.</p>}<Link className="inline-link" href={`/${locale.toLowerCase()}/mortgage-calculator/methodology`}>Read the full methodology <span aria-hidden="true">→</span></Link></div></section>
    <section className="methodology faq-section" id="faq"><div><p className="eyebrow">FAQ</p><h2>What this estimate does and does not include.</h2><p>Open a question for the full answer. The first answer is shown by default.</p></div><div className="faq-list">{localeFaq[locale].map((item, index) => <details key={item.question} open={index === 0}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div></section>
    <footer className="site-footer"><span>© 2026 MortgageBreezy</span><span>Estimate only. Not a loan offer, tax opinion, or financial advice.</span><Link href={`/${locale.toLowerCase()}/mortgage-calculator/privacy`}>Privacy</Link><Link href={`/${locale.toLowerCase()}/mortgage-calculator/legal-notice`}>Legal notice</Link></footer>
  </main>;
}
